# Generated by Django 4.1.13 on 2025-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id_doc',
            field=models.FileField(blank=True, null=True, upload_to='id_docs/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
