# Generated by Django 4.1.13 on 2025-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0002_alter_voter_email_alter_voter_id_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='unique_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
