# Generated by Django 4.1.13 on 2025-02-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0003_voter_password_voter_unique_id_alter_voter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
