# Generated by Django 4.1.13 on 2025-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0004_alter_voter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='password',
        ),
        migrations.AddField(
            model_name='voter',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
