# Generated by Django 4.1.13 on 2025-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id_doc',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
