# Generated by Django 4.1.13 on 2025-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0007_alter_voter_id_doc_alter_voter_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
