# Generated by Django 4.1.13 on 2025-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0008_alter_voter_id_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
