# Generated by Django 4.1.13 on 2025-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0009_voter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('profile_photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='unique_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
