# Generated by Django 4.1.13 on 2025-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0010_userprofile_alter_voter_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
