# Generated by Django 5.1.6 on 2025-05-29 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0029_poll_alter_voter_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$tIHcwp11eydzpShTJSgdaV$UyuQdH4+yI6sSWBFMGvAwrVceDflxpr1aCk8OF83LtM=', max_length=128),
        ),
    ]
