# Generated by Django 5.1.6 on 2025-05-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0030_userprofile_user_alter_voter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='myprojectdpoll.poll'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$HmfavzwphQ2NXytLoOOL6z$b8qauHE/CvYMujTu3zgcd9vRWJYnnuz9LGSi6szbCC0=', max_length=128),
        ),
    ]
