# Generated by Django 5.1.6 on 2025-06-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectdpoll', '0031_candidate_poll_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprojectdpoll.voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$S7w7CapbdkjdZArfbNNCtc$Ss94KAA0Qb+7XAWfvljcNU8L9lsfp1kk2yqa9QGlTsY=', max_length=128),
        ),
    ]
